#!/bin/bash
bq mk --time_partitioning_type=DAY stockexchange.gbpusd_201401p
for (( i=1; i<=31; i++ ))
do
    if [[ $i -lt 10 ]]; then
        n="0$i"
    else
        n=$i  
    fi
    bq query --use_legacy_sql=false --replace --destination_table 'stockexchange.gbpusd_201401p$201401'$n "SELECT * from stockexchange.gbpusd_201401 WHERE EXTRACT(DAY from DATE(time))=$i ORDER BY time;"
done
